### ISSUE TITLE
BUG found in metis program: Active.checkSaturated

### ISSUE THREAD

**Issue by 01mf02** [gilith/metis#6]
When running Metis 2.3-20170925 (compiled with PolyML 5.7) on some [problems](https://github.com/gilith/metis/files/1353473/problems.zip), I obtain the error message:

    FATAL ERROR: BUG found in metis program:
    Active.checkSaturated

**Comment by gilith** [comment]
Argh: that shouldn't happen!

Thanks for the bug report, I'll investigate this.

**Comment by gilith** [comment]
I've finished my investigation, and it turns out each problem exposed a different issue in the code.

meson443.p is really satisfiable, but the debug check on the saturation set was too strict and failed, causing the bug.

meson985.p is really unsatisfiable, but saturated because the procedure for generating factors of a derived clause was broken whenever the largest literals were simplified away (e.g., ~(biggest_literal = $x) \/ other_literals).

Thanks again for the bug report, I have made a new release that fixes both these issues, and will shortly push a commit that formally closes this issue.
